// AUTH REDUCER TYPES
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
export const MODIFY_USER = "MODIFY_USER"

// ERROR REDUCER TYPES
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"

// TUTOR REDUCER TYPES
export const TUTOR_ADD_SUCCESS = "TUTOR_ADD_SUCCESS"
export const DELETE_SUCCES = "DELETE_SUCCESS"
export const MODIFY_SUCCESS = "MODIFY_SUCCESS"
export const TUTOR_ADD_FAIL = "TUTOR_ADD_FAIL"
export const DELETE_FAIL = "DELETE_FAIL"
export const MODIFY_FAIL = "MODIFY_FAIL"

// LEARNER REDUCER TYPES
export const LEARNER_ADD_SUCCESS = "LEARNER_ADD_SUCCESS"
export const LEARNER_ADD_FAIL = "LEARNER_ADD_FAIL"

// APPS REDUCER TYPES
export const APP_LOAD_SUCCESS = "APP_LOAD_SUCCESS"
export const APP_LOAD_FAIL = "APP_LOAD_FAIL"
export const APP_LOADING = "APP_LOADING"

// ORG REDUCER TYPES
export const ORG_LOADED = "ORG_LOADED"
export const ORG_LOADING = "ORG_LOADING"
export const ORG_LOAD_FAIL = "ORG_LOAD_FAIL"

// REQ REDUCER TYPES
export const REQ_LOADED = "REQ_LOADED"
export const REQ_LOADING = "REQ_LOADING"
export const REQ_LOAD_FAIL = "REQ_LOAD_FAIL"